### ISSUE TITLE
Exception on copy text from ant build file

### ISSUE THREAD

**Issue by gandalfmagic** [ganoro/phing-eclipse#1]
When I open eclipse, I get the following error:

**Could not create content describer for org.ganoro.phing.core.antBuildFile. Content type has been disabled.
whithout a stack trace.**

When I open an ant build file I get:

**The 'com.dubture.symfony.ui.yamlHyperlinkDetector' extension from plug-in 'com.dubture.symfony.ui' to the 'org.eclipse.ui.workbench.texteditor.hyperlinkDetectors' extension point will be ignored because it contains invalid attributes.
whithout a stack trace.**

And when I try to copy some text, I get:

**Plug-in org.ganoro.phing.ui was unable to load class org.eclipse.ant.internal.ui.editor.AntElementHyperlinkDetector.**

**java.lang.ClassNotFoundException: org.eclipse.ant.internal.ui.editor.AntElementHyperlinkDetector
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:513)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:345)
    at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1207)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.ui.texteditor.HyperlinkDetectorDescriptor$1.run(HyperlinkDetectorDescriptor.java:102)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.texteditor.HyperlinkDetectorDescriptor.createHyperlinkDetector(HyperlinkDetectorDescriptor.java:114)
    at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:72)
    at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:286)
    at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:258)
    at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:462)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:211)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3588)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3209)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)**

If I remove the Phing extension, the first and last errors stops from showing up.

**Comment by shakaran** [comment]
I am getting the same "Could not create content describer for org.ganoro.phing.core.antBuildFile. Content type has been disabled." in Eclipse 4.6 :

```
 !SESSION 2016-05-02 00:58:10.153 -----------------------------------------------
eclipse.buildId=4.6.0.I20160128-2000
java.version=1.8.0_03-Ubuntu
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_ES
Framework arguments:  -product org.eclipse.epp.package.php.product -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.php.product -clean -clearPersistedState -consoleLog

!ENTRY org.eclipse.core.resources 2 10035 2016-05-02 00:58:19.056
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
log4j:WARN No appenders could be found for logger (org.eclipse.jgit.util.FS).
log4j:WARN Please initialize the log4j system properly.

!ENTRY org.eclipse.jface 2 0 2016-05-02 00:58:26.661
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-05-02 00:58:26.668
!MESSAGE A conflict occurred for CTRL+G:
Binding(CTRL+G,
    ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace,Declaration in Workspace,
        Search for declarations of the selected element in the workspace,
        Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@70b630d,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+G,
    ParameterizedCommand(Command(org.pdtextensions.core.ui.generategetters,Generate Getters and Setters,
        Generate Getters and Setters,
        Category(org.eclipse.ui.category.edit,Edit,null,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@72e1e587,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2016-05-02 00:58:26.670
!MESSAGE A conflict occurred for ALT+SHIFT+D Q:
Binding(ALT+SHIFT+D Q,
    ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.debug,Debug Ant Build,
        Debug Ant Build,
        Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5036a286,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+D Q,
    ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.debug,Debug Phing Build,
        Debug Phing Build,
        Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@73818435,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2016-05-02 00:58:26.671
!MESSAGE A conflict occurred for ALT+SHIFT+X Q:
Binding(ALT+SHIFT+X Q,
    ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.run,Run Ant Build,
        Run Ant Build,
        Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2fce8243,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+X Q,
    ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.run,Run Phing Build,
        Run Phing Build,
        Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
        org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@52fe87e0,
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.core.contenttype 4 0 2016-05-02 00:58:34.447
!MESSAGE Could not create content describer for org.ganoro.phing.core.antBuildFile. Content type has been disabled.

!ENTRY org.eclipse.debug.ui 4 0 2016-05-02 00:58:35.531
!MESSAGE Tab group extension: org.eclipse.ant.ui.launchConfigurationTabGroup.ant for type org.eclipse.ant.AntLaunchConfigurationType for the [*] mode has been replaced by extension: org.eclipse.ant.ui.launchConfigurationTabGroup.ant

!ENTRY org.eclipse.debug.ui 4 0 2016-05-02 00:58:35.532
!MESSAGE Tab group extension: org.eclipse.ant.ui.launchConfigurationTabGroup.ant.builder for type org.eclipse.ant.AntBuilderLaunchConfigurationType for the [*] mode has been replaced by extension: org.eclipse.ant.ui.launchConfigurationTabGroup.ant.builder
```
